export const SITE_NAME = "MK";
export const SITE_DESCRIPTION =
  "Original paintings and limited edition prints. Discover unique contemporary artwork.";
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Collections", href: "/collections" },
  { label: "About", href: "/about" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
] as const;

export const PLACEHOLDER_COLLECTIONS = [
  {
    _id: "1",
    title: "Abstract",
    slug: "abstract",
    description: "Bold expressions of color and form",
    artworkCount: 12,
    image: null as never,
  },
  {
    _id: "2",
    title: "Figurative",
    slug: "figurative",
    description: "Exploring the human form and emotion",
    artworkCount: 8,
    image: null as never,
  },
  {
    _id: "3",
    title: "Landscapes",
    slug: "landscapes",
    description: "Capturing light and atmosphere",
    artworkCount: 10,
    image: null as never,
  },
];

export const PLACEHOLDER_ARTWORKS = [
  {
    _id: "a1",
    title: "The Edge of Seeing",
    slug: "the-edge-of-seeing",
    description: "An exploration of light through layered oils on canvas.",
    medium: "Oil on Canvas",
    dimensions: '36" × 48"',
    year: 2024,
    price: 4075,
    currency: "USD",
    status: "available" as const,
    collection: { _id: "1", title: "Abstract", slug: "abstract" },
    image: null as never,
    images: [],
    featured: true,
  },
  {
    _id: "a2",
    title: "Luminescence",
    slug: "luminescence",
    description: "Soft washes of color capture the fleeting quality of twilight.",
    medium: "Acrylic on Canvas",
    dimensions: '24" × 30"',
    year: 2024,
    price: 1698,
    currency: "USD",
    status: "available" as const,
    collection: { _id: "1", title: "Abstract", slug: "abstract" },
    image: null as never,
    images: [],
    featured: true,
  },
  {
    _id: "a3",
    title: "Somewhere Between",
    slug: "somewhere-between",
    description: "A meditation on the spaces between memory and reality.",
    medium: "Mixed Media",
    dimensions: '30" × 40"',
    year: 2023,
    price: 1359,
    currency: "USD",
    status: "sold" as const,
    collection: { _id: "2", title: "Figurative", slug: "figurative" },
    image: null as never,
    images: [],
    featured: true,
  },
  {
    _id: "a4",
    title: "Standstill",
    slug: "standstill",
    description: "Capturing a moment of perfect stillness in the chaos.",
    medium: "Oil on Canvas",
    dimensions: '40" × 50"',
    year: 2024,
    price: 2038,
    currency: "USD",
    status: "available" as const,
    collection: { _id: "3", title: "Landscapes", slug: "landscapes" },
    image: null as never,
    images: [],
    featured: true,
  },
  {
    _id: "a5",
    title: "Between Drops",
    slug: "between-drops",
    description: "The beauty found in rain-washed urban landscapes.",
    medium: "Oil on Panel",
    dimensions: '24" × 36"',
    year: 2023,
    price: 1698,
    currency: "USD",
    status: "available" as const,
    collection: { _id: "3", title: "Landscapes", slug: "landscapes" },
    image: null as never,
    images: [],
    featured: false,
  },
  {
    _id: "a6",
    title: "Passing Lights",
    slug: "passing-lights",
    description: "City lights reflected in wet pavement after dark.",
    medium: "Oil on Canvas",
    dimensions: '36" × 48"',
    year: 2024,
    price: 2038,
    currency: "USD",
    status: "available" as const,
    collection: { _id: "3", title: "Landscapes", slug: "landscapes" },
    image: null as never,
    images: [],
    featured: true,
  },
];
